# Generated by Django 5.1.3 on 2024-11-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTFSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the GTFS dataset', max_length=100)),
                ('file', models.FileField(help_text='Upload GTFS zip file', upload_to='gtfs_static_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
