# Generated by Django 5.1.3 on 2024-11-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_id'),
        ('gtfs', '0002_gtfsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrestriction',
            name='calendar_pattern',
        ),
        migrations.RemoveField(
            model_name='bookingrestriction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookingrestriction',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='bookingrestriction',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bookingrestriction',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtfs.route'),
        ),
        migrations.AlterField(
            model_name='bookingrestriction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrestriction',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
